version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wind-alert-go"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ikm1iesw80mi"
s3_prefix = "wind-alert-go"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
